<template>
  <VToolbar
    color="primary"
    dark
    app
  >
    <VToolbarTitle
      class="headline text-uppercase"
    >
      <span
        v-text="'Api'"
      />
      <span
        class="font-weight-light"
        v-text="'News'"
      />
    </VToolbarTitle>
    <VBtn
      flat
      class="font-weight-regular"
      to="/"
      v-text="'Home'"
    />
     <VBtn
      flat
      class="font-weight-regular"
      to="/contactPage"
      v-text="'Contact'"
    />
    <VSpacer />
    <VBtn
      flat
      small
      href="https://github.com/kammradt/faculdade-webdev"
      target="_blank"
      v-text="'Github'"
    />
  </VToolbar>
</template>
